# Generated by Django 3.0.5 on 2020-04-12 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['cor'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200, null=True)),
                ('MBL', models.IntegerField(default=0)),
                ('GBL', models.IntegerField(default=0)),
                ('P', models.IntegerField(default=0)),
                ('M', models.IntegerField(default=0)),
                ('G', models.IntegerField(default=0)),
                ('GG', models.IntegerField(default=0)),
                ('movimentacao', models.CharField(default='Entrada', max_length=200)),
                ('cor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.Cores')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
    ]
