# Generated by Django 3.0.5 on 2020-04-12 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cores',
            name='cor',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='cor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.Cores', to_field='cor'),
        ),
    ]
