# Generated by Django 3.0.5 on 2020-04-12 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20200412_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.AlterField(
            model_name='estoque',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.Tipos', to_field='tipo'),
        ),
    ]
