# Generated by Django 3.0.5 on 2020-04-12 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20200412_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['data']},
        ),
    ]
