# Generated by Django 3.0.5 on 2020-04-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
