# Generated by Django 3.0.5 on 2020-04-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_delete_clientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['tipo']},
        ),
    ]
