# Generated by Django 3.0.5 on 2020-04-13 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200413_0105'),
        ('estoque', '0010_auto_20200412_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=200)),
                ('estampa', models.CharField(blank=True, max_length=200, null=True)),
                ('etiquetagem', models.BooleanField(default=False)),
                ('estampada', models.BooleanField(default=False)),
                ('pronta_entrega', models.BooleanField(default=False)),
                ('observacoes', models.CharField(blank=True, default='', max_length=100)),
                ('cor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.Cores', to_field='cor')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.Tipos', to_field='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_acordado', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Clientes', to_field='nome')),
            ],
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.Pedido')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.Produtos')),
            ],
        ),
    ]
