# Generated by Django 3.0.5 on 2020-04-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_auto_20200413_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
