# Generated by Django 3.0.5 on 2020-04-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_pedido_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data']},
        ),
        migrations.AddField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
