# Generated by Django 3.0.5 on 2020-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_auto_20200413_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, default='Ativo', max_length=100),
        ),
    ]
