# Generated by Django 3.0.5 on 2020-04-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200413_0105'),
        ('estoque', '0015_auto_20200413_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Pedidos',
        ),
    ]
