# Generated by Django 3.0.5 on 2020-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_auto_20200413_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='prazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
