# Generated by Django 3.0.5 on 2020-04-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_pedidos_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
