# Generated by Django 3.0.5 on 2020-04-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_auto_20200413_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedido',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
    ]
