# Generated by Django 3.0.5 on 2020-04-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('telefone', models.CharField(max_length=200, null=True)),
                ('endereco', models.CharField(max_length=200, null=True)),
                ('data_criado', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
