# Generated by Django 3.0.5 on 2020-04-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200412_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
