# Generated by Django 3.0.5 on 2020-04-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_clientes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='email',
        ),
    ]
